version: "3"

services:
  web:
    build:
      ./koken
    volumes:
      - "./koken:/var/www/html"
    ports:
      - "8001:80"
    networks:
      - web-network
    deploy:
      replicas: 1
      restart_policy:
        condition: always
  db:
    image: mysql:8
    networks:
      - web-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password

networks:
  web-network
